# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afield', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
