# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afield', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='no name specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='no description specified', max_length=200),
        ),
    ]
