# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afield', '0005_auto_20160822_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomaction',
            name='nextRoom',
            field=models.IntegerField(default=0),
        ),
    ]
