# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afield', '0006_roomaction_nextroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomaction',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afield.Room'),
        ),
    ]
